# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bleuprint/all/bleuprint.rbi
#
# bleuprint-0.1.4

module Bleuprint
end
module Bleuprint::Services
end
module Bleuprint::Services::ActiveRecord
end
class Bleuprint::Services::ActiveRecord::HumanizeModelErrors
  def call!; end
  def initialize(instance); end
  def instance; end
end
