# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/minitest-rg/all/minitest-rg.rbi
#
# minitest-rg-5.3.0

module Minitest
  def self.plugin_rg_init(options); end
  def self.plugin_rg_options(opts, _options); end
end
class Minitest::RG
  def colors; end
  def initialize(io, colors = nil); end
  def io; end
  def method_missing(msg, *args); end
  def print(output); end
  def puts(output = nil); end
  def respond_to_missing?(method_name, include_all = nil); end
  def self.rg!(color: nil); end
  def self.rg?; end
end
